config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  get 'malls', to: 'malls#index'
  get 'malls/new', to: 'malls#new'
  post 'malls/new', to: 'malls#create'
  get 'malls/:id', to: 'malls#show'
  resources :malls

  resources :items
  
  get "items/new", to:"items#new"
  post "items", to: "items#create"
  get "items", to: "items#index"
  get "items/:id", to: "items#show"
  
  
  

  devise_for :users
  
  get 'users', to: "users#index"

  get 'users/:id', to: "users#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    validates :item_name, :item_info, :available_in, :item_price, presence: true
    validate  :picture_size
    belongs_to :mall
    mount_uploader :picture, PictureUploader
    
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
    
end

app/models/mall.rb
class Mall < ApplicationRecord
    validate  :picture_size
    mount_uploader :picture, PictureUploader
    has_many :items
    
    private
    #private will make the picture_size only within this code
    def picture_size
      if :picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:first_name, :last_name, :email, :current_password, :password, :password_confirmation)
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: :index
  
  def index
    @items = Item.all
    @item_list_comparison = @items.group_by(&:item_name)
  end
    
  def show
    @item = Item.find(params[:id])
    @items= Item.all
    @item_list_comparison = @items.group_by(&:item_name)
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: "You have registered a new item" }
      else 
        format.html {render 'new'}
      end
    end
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    respond_to do |format|
      if @item.update_attributes(item_params)
        flash[:success] = "You have succesfully updated the item"
        format.html { redirect_to @item }
      else
        format.html { :edit }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html {redirect_to items_path, notice: "The item has been deleted"}
    end
  end
    

  private
  
  def item_params
    params.require(:item).permit(:item_name, :item_info, :mall_name, :available_in, :item_price, :picture)
  end

end

app/controllers/malls_controller.rb
class MallsController < ApplicationController
  
  def index
    @malls = Mall.all
    @malls_list = @malls.group_by(&:mall_name)
  end
  
  def show 
    @mall = Mall.find(params[:id])
  end
  
  def new
    @mall = Mall.new
  end
  
  def create
    @mall = Mall.new(mall_params)
    respond_to do |format|
     if @mall.save
       format.html { redirect_to items_path, notice: "You have registered a new mall" }
     else
       format.html { render 'new' }
     end
   end
  end
  
  def edit
    @mall = Mall.find(params[:id])
  end
  
  def update
    @mall = Mall.find(params[:id])
    respond_to do |format|
      if @mall.update_attributes(mall_params)
        flash[:success] = "You have succesfully updated the mall"
        format.html { redirect_to @mall }
      else
        format.html { :edit }
      end
    end
  end

  private
  
  def mall_params
    params.require(:mall).permit(:mall_name, :mall_address, :mall_contact, :picture)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
  end
  
  def current_user?(user)
    user == current_user
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    
#   def resource_name
#     :item
#   end
 
#   def resource
#     @resource ||= Item.new
#   end
 
#   def devise_mapping
#     @devise_mapping ||= Devise.mappings[:item]
#   end
  
end

app/helpers/malls_helper.rb
module MallsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
<%= render "devise/shared/error_messages", object: f.object %>

  <div class="field">
    <%= f.label :item_name %><br />
    <%= f.text_field :item_name, autofocus: true %>
  </div>
  
  <div class="field">
    <%= f.label :item_info %><br />
    <%= f.text_area :item_info %>
  </div>
  
  <div class="field">
    <%= f.label :mall_name %><br />
    <!--<#select_tag :mall, options_from_collection_for_select(Mall.all, "id", "mall_name") %>-->
    <%= f.collection_select(:mall_name, Mall.all, :mall_name, :mall_name,  prompt: true) %>
  </div>
  
    <div class="field">
    <%= f.label :available_in %><br />
    <%= f.text_field :available_in, placeholder: "Aeon, Watson or..."  %>
  </div>
  
  <div class="field">
    <%= f.label :item_price %><br />
    <%= f.number_field :item_price,  value: number_to_currency(f.object.item_price.to_f, delimiter: '', unit: ''), step: 0.01 %>
  </div> 

 <span class="picture">
   <%= f.label :picture %>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<br>
  <div class="actions">
    <%= f.submit yield(:button_text) %>
  </div>
<% end %>
  

<script type="text/javascript">
  $('#item_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/items/edit.html.erb
<% provide(:button_text, 'Update the item') %>

<h1>Editting the item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">All items</h1>
                </div>

    <!-- /#wrapper -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            All items
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table id= "items" width="100%" class="table table-striped table-bordered table-hover sssss">
                                
                                <thead>
                                    <tr>
        <th>Item name</th>
        <th>Item info</th>
        <th>Mall</th>
        <th>Available in</th>
        <th>Price</th>

    </tr>
    </thead>
    <tbody>
<% @item_list_comparison.each do |item_name, item| %>
<% item.each do |i| %>
    <tr>
        <td><%= link_to i.item_name, i %></td>
        <td><%= i.item_info %></td>
        <td><%= i.mall_name %></td>
        <td><%= i.available_in %></td>
        <td><%= i.item_price %></td>
    </tr>
    <% end %>
     <% end %>
     </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>
    
    
    
    
  

app/views/items/new.html.erb
<% provide(:button_text, 'Register the item') %>
<h2>New item registration</h2>

<%= render 'form' %> 

app/views/items/show.html.erb
<h1>Item details</h1>
<div class="panel-body">
<table id= "items" width="100%" class="table table-striped table-bordered table-hover">

<p>Item name: <%= @item.item_name %></p>


<%= image_tag @item.picture.url if @item.picture? %>

<div class="panel-body">
<table id= "items" width="100%" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
        <th>Item information</th>
        <th>Mall</th>
        <th>Available in</th>
        <th>Price</th>
        </tr>
    </thead>
    <tbody>

<% @item_list_comparison.each do |item_name, item| %>
<% item.each do |i| if item_name == @item.item_name %>
<tr>
<td><%= i.item_info %></td>
<td><%= i.mall_name %></td>
<td><%= i.available_in %></td>
<td><%= i.item_price %></td>
<td>
<% if current_user.admin? %>
  | <%= link_to "Delete", @item, method: :delete, data: {confirm: "Are you sure?"} %>
</td>
<% end %>
<% end %>
<% end %>
</tr>
<% end %>
</tbody>
    </table>
    </div>
    </div>

<!--<%= link_to "Edit item", edit_item_path %>-->

app/views/layouts/_flash_message.html.erb
<div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12" style="margin-top: 10px;">
            <% if flash.any? %>
              <% flash.each do |key, message| %>
                <% if key == "notice" || key == "success" %>
                   <div class="alert alert-info">
                      <%= message %>
                   </div>
                <% elsif key == "error" || key == "warning" %>
                   <div class="alert alert-danger">
                      <%= message %>
                   </div>
                <% end %>
              <% end %>
            <% end %>
            </div>
          </div>
          

app/views/layouts/_nav_section.html.erb
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
           <!-- /.dropdown-messages -->
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="/items/new">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New item
                                    <span class="pull-right text-muted small"></span>
                                </div>
                            </a>
                        </li>
                        <!--<li class="divider"></li>-->
                        <!--<li>-->
                        <!--    <a href="#">-->
                        <!--        <div>-->
                        <!--            <i class="fa fa-twitter fa-fw"></i> 3 New Followers-->
                        <!--            <span class="pull-right text-muted small">12 minutes ago</span>-->
                        <!--        </div>-->
                        <!--    </a>-->
                        <!--</li>-->
                        <!--<li class="divider"></li>-->
                        <!--<li>-->
                        <!--    <a href="#">-->
                        <!--        <div>-->
                        <!--            <i class="fa fa-envelope fa-fw"></i> Message Sent-->
                        <!--            <span class="pull-right text-muted small">4 minutes ago</span>-->
                        <!--        </div>-->
                        <!--    </a>-->
                        <!--</li>-->
                        <!--<li class="divider"></li>-->
                        <!--<li>-->
                        <!--    <a href="#">-->
                        <!--        <div>-->
                        <!--            <i class="fa fa-tasks fa-fw"></i> New Task-->
                        <!--            <span class="pull-right text-muted small">4 minutes ago</span>-->
                        <!--        </div>-->
                        <!--    </a>-->
                        <!--</li>-->
                        <!--<li class="divider"></li>-->
                        <!--<li>-->
                        <!--    <a href="#">-->
                        <!--        <div>-->
                        <!--            <i class="fa fa-upload fa-fw"></i> Server Rebooted-->
                        <!--            <span class="pull-right text-muted small">4 minutes ago</span>-->
                        <!--        </div>-->
                        <!--    </a>-->
                        <!--</li>-->
                        <!--<li class="divider"></li>-->
                        <!--<li>-->
                        <!--    <a class="text-center" href="#">-->
                        <!--        <strong>See All Alerts</strong>-->
                        <!--        <i class="fa fa-angle-right"></i>-->
                        <!--    </a>-->
                        <!--</li>-->
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="<%= edit_user_registration_path %>"><i class="fa fa-gear fa-fw"></i> Edit Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="/users/sign_out" data-method= "delete"><i class="fa fa-gear fa-fw"></i> Sign out</a>
                        <!-- link_to "Sign out", destroy_user_session_path, method: :delete -->
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul> 
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="/users"><i class="fa fa-dashboard fa-fw"></i> Users</a>
                        </li>
                        <li>
                            <a href="/malls"><i class="fa fa-dashboard fa-fw"></i> Malls</a>
                        </li>
                        <li>
                            <a href="/items"><i class="fa fa-dashboard fa-fw"></i> Items</a>
                        </li>

                        
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
            </nav>

app/views/layouts/application.html.erb
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  <title>ShopSmart</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
  <!-- Bootstrap Core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    
    
    
</head>
<body>

    <div id="wrapper">
        

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/items">ShopSmart</a>
            </div>
            <!-- /.navbar-header -->

            <%= render "/layouts/nav_section" %>
            <%= render "/layouts/flash_message" %>
            <!-- when rendering partial no need include underscore in the link -->
            
            <!--<div class="col-lg-4 col-md-6">-->
            <!--        <div class="panel panel-yellow">-->
            <!--            <div class="panel-heading">-->
            <!--                <div class="row">-->
            <!--                    <div class="col-xs-3">-->
            <!--                        <i class="fa fa-shopping-cart fa-5x"></i>-->
            <!--                    </div>-->
            <!--                    <div class="col-xs-9 text-right">-->
            <!--                        <div class="huge">Hot Deals!!</div>-->
            <!--                        <div></div>-->
            <!--                    </div>-->
            <!--                </div>-->
            <!--            </div>-->
            <!--            <a href="#">-->
            <!--                <div class="panel-footer">-->
            <!--                    <span class="pull-left">View Details</span>-->
            <!--                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>-->
            <!--                    <div class="clearfix"></div>-->
            <!--                </div>-->
            <!--            </a>-->
            <!--        </div>-->
            <!--    </div>-->
            
          <%= yield %>
            </div>

 <!-- jQuery -->
    <script src="/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/dist/js/sb-admin-2.js"></script>
    
    <%= javascript_include_tag 'dataTables/jquery.dataTables.js' %>
    
    <%= javascript_include_tag 'dataTables/bootstrap/3/jquery.dataTables.bootstrap.js' %>

    
    
    
    
      <script>
        
        
        
 
    $( document ).ready(function() {
$('.sssss').dataTable({
  // ajax: ...,
  // autoWidth: false,
  // pagingType: 'full_numbers',
  // processing: true,
  // serverSide: true,

  // Optional, if you want full pagination controls.
  // Check dataTables documentation to learn more about available options.
  // http://datatables.net/reference/option/pagingType
});
});

   </script>
</body>
</html>

app/views/malls/_form.html.erb
<%= form_for(@mall) do |f| %>
<%= render "devise/shared/error_messages", object: f.object %>

<div class="field">
<%= f.label :mall_name %><br />
<%= f.text_field :mall_name, autofocus: true %>
</div>

<div class="field">
<%= f.label :mall_address %><br />
<%= f.text_field :mall_address %>
</div>

<div class="field">
<%= f.label :mall_contact %><br />
<%= f.text_field :mall_contact %>
</div>

<span class="picture">
<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
</span>

<div class="actions">
<%= f.submit yield(:button_text) %>
</div>
<% end %>

<script type="text/javascript">
  $('#item_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/malls/edit.html.erb
<% provide :button_text, 'Update the mall' %>
<h2>Updating the mall</h2>

<%= render 'form' %>

app/views/malls/index.html.erb
<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Malls in your area</h1>
                </div>

    <!-- /#wrapper -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            All malls
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table id= "items" width="100%" class="table table-striped table-bordered table-hover">
                                
                                <thead>
                                    <tr>
        <th>Mall</th>
    </tr>
    </thead>
    <tbody>
<% @malls_list.each do |mall_name, mall| %>
<% mall.each do |i| %>
    <tr>
        <td><%= link_to i.mall_name, i %></td>
    </tr>
    <% end %>
    <% end %>
    <% if  current_user.try(:admin?) %>
    <%= link_to "New malls?", new_mall_path %>
    <% end %>
     </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>

app/views/malls/new.html.erb
<% provide :button_text, "Register new mall" %>
<h2>New Mall registration</h2>

<%= render 'form' %>

app/views/malls/show.html.erb
<%= image_tag @mall.picture.url if @mall.picture? %>
<h1><%= @mall.mall_name %></h1>
<p>Address: <%= @mall.mall_address %></p>
<p>Contact: <%= @mall.mall_contact %></p>

<% if  current_user.try(:admin?) %>
<%= link_to "Edit mall detail?", edit_mall_path %>
<% end %>

app/views/users/index.html.erb
<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">User</h1>
                </div>

    <!-- /#wrapper -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            All users
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>

    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
    <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
    </tr>
    <% end %>
    </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>